jmakhack/hydrate-reminder

build.gradle, src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #29
Add command handler for resetting the current hydrate reminder interval by making use of the existing `resetHydrateReminderTimeInterval` method.
After the reset is successful, a chat message is displayed to let the player know that the interval has been successfully reset.
RuneLite Version: 1.7.7
=> Reset command

src/main/java/com/hydratereminder/HydrateReminderCommandArgs.java, src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #32
Shows all available hydrate commands when `::hydrate help` is executed.
If the player inputs an invalid command such as `::hydrate xyz`, an error message is displayed in chat followed by the help message showing all the available hydrate commands.
RuneLite Version: 1.7.7
=> Add help command

src/main/java/com/hydratereminder/HydrateReminderConfig.java, src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #31
Added 12 different welcome messages that display as a chat message on player login.\
Two of the 12 messages inform the player of the existence of hydrate chat commands.\
A 500ms delay is added to the posting of the message so that the official OSRS welcome message always gets displayed first in the chat window.
Added a toggle-able configuration setting for the welcome message that is enabled by default.
RuneLite Version: 1.7.7
=> Add hydrate welcome message

src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #40
Instead of relying on using a timer to send the hydrate reminder welcome message after the usual OSRS welcome message, this solution sends the welcome message on the first game tick after each login.
Once the hydrate reminder welcome message is sent, a flag is set to false so that repeated welcome messages are not sent.
=> Fix welcome message duplication issue

src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #20 
Added a variety of new messages for the hydrate reminder plugin to cycle through.
=> Add a variety of hydrate reminder messages

src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #52
Closes #54 
Instead of checking for the LOGGED_IN state when doing the hydrate reminder initialization logic, the code now checks for the LOGGING_IN state. This is done because there are many instances where a player's state will change into the LOGGED_IN state such as going into and exiting a special event and also when hopping between worlds.
=> Fix welcome message displaying during events issue

src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #67
I added a method to take in charge the string formatting, and i used it in the methods that have the logic behind "::hydrate next" and "::hydrate  prev"
By testing 3 cases: 1 , 0 and a different number than these two.
I couldn't test that in rs, as i don't play the game and i don't know how to set it up.
=> [FIX] Hours, minutes, and seconds are always displayed as plural for next and prev commands

src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #60
Removed the unnecessary spacing at the start of broadcast messages from the hydrate reminder plugin.
=> Remove unnecessary broadcast message spacing

src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #66
solved by using a string builder to append the segments as needed
Tested by inputting several different values into the time interval config field
Operating System: Windows 10 pro 20H2
RuneLite Version:  1.7.15
=> Changes time next/prev string to only display segments as needed

src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #58
Move the logic for loading the hydrate emoji out from the LOGGING_IN state check and into the code that runs on the first game tick. This way the emoji will be loaded even if the LOGGING_IN state is never triggered.
Note: This is just a screenshot to show that the normal functionality is still working. Unfortunately, the install functionality cannot be fully tested until after it is released on the plugin hub.
=> Fix emoji loading issue on plugin install

src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #76
Change the `getTimeDisplay` helper method to only return the time part of the string instead of the full string. As a result, the methods that handle the prev and next commands can append the correct text to the end of the time display as needed.
=> Fix wrong text display for prev command

build.gradle, src/main/java/com/hydratereminder/HydrateReminderCommandArgs.java, src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #84
Added shortened commands to the `HydrateReminderCommandArgs` enum.
Updated the switch statement in the `onCommandExecuted`  method of the `HydrateReminderPlugin` class.
Passed all tests, and works as expected in game.
Operating System: Windows 10
RuneLite Version: 1.7.18
Using the `::hr n` command in game
=> Added support for shortened commands.

src/main/java/com/hydratereminder/HydrateReminderCommandArgs.java, src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/test/java/com/hydratereminder/HydrateReminderCommandArgsTest.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
References #88 
Partially completes issue #88, implemented tracking of the number of hydration breaks over the duration of the current session only. This does not track the overall total number of hydration breaks across distinct game sessions.
Commands added: <code>::hydrate total</code> and <code>::hydrate t</code>, both to display a message indicating the number of hydration breaks taken.
Updated the <code>HydrateReminderCommandArgsTest</code> class to reflect the additional commands
Updated the unit tests in <code>HydrateReminderPluginTest</code> to validate correct functionality for the <code>incrementCurrentSessionHydrationBreaks</code> method which updates the number of breaks taken; also added a <code>@Before</code> method to instantiate a new <code>HydrateReminderPlugin</code> …
=> Total hydration breaks

src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #83 
After a reset command is triggered, there is a reset flag that is set to true. Any following prev command uses will display the correct text indicating the amount of time that has passed since the reset occurred. When the next hydration break occurs, the reset flag is set back to false so the prev command will go back to displaying the amount of time since that break.
RuneLite Version: 1.7.18
=> Fix prev command to account for resets

src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/main/java/com/hydratereminder/HydrateReminderTimer.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #65
Created a new HydrateReminderTimer class which extends from the InfoBox class. This new class creates the new infobox to display on the overlay with the countdown timer based on when the next hydrate break is to occur. Whenever a player logs in, the timer is created and rendered onto the upper left overlay.
Note: Unit tests to be added in a separate issue. 
RuneLite Version: 1.7.22
=> Add hydrate reminder timer infobox to overlay

src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #139
This commit had the purpose to uncomment an existing test that would check if the method getDurationSinceLastBreak from the HydrateReminderPlugin class would return the correct duration.
To make this test work, I added a second parameter to the method which represents the current Instant. This way it was possible in the test to mock two instants so that they would always have a duration of 1 hour between them.
Due to the change in the method parameters, the code where this method was used was refactored to reflect this changes without changing how the code worked previously
=> Test getDurationSinceLastBreak returns correct duration

.gitignore, build.gradle, src/main/java/com/hydratereminder/HydrateReminderCommandArgs.java, src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/test/java/com/hydratereminder/HydrateReminderCommandArgsTest.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes issue #145 add hydrate chat command done
Implemented hydrate command by calling the reset command and using the increment hydration method, problems could ariese of the implementation of reset command changes. 
Ran the unit test and tested it in game, all seems to work okey
Operating System: Windows 10 Home version 21H1
RuneLite Version: 1.8.27
=> Ticket issue 145 add hydrate command

build.gradle, src/main/java/com/hydratereminder/HydrateBreakMessageDictionary.java, src/main/java/com/hydratereminder/HydrateReminderConfig.java, src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java, src/main/java/com/hydratereminder/HydrateReminderPlugin.java, src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java, src/test/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionaryTest.java
Closes #144
Adding the ability to choose personality type - either fun or straightforward.
Personality type is used to choose proper message set when notifying about hydrate break.
RuneLite Version: 1.8.29
=> Add personalised hydration break messages

src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java, src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
Closes #194 
Added the CARING personality inside [HydrateReminderPersonalityType.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java).
Added the CARING dictionary into a separate function and then added the option to the switch case inside [HydrateBreakMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java)
No testing has been done, as the change only adds a new option for the hydration message sent to users. No new functionality was added nor a change in the project functionality was done. <br>
However, testing will be done if required.
=> Added caring personality and dictionary for hydration reminder

src/main/java/com/hydratereminder/HydrateReminderTimer.java
Show informative tooltip when mouse is hovered over infobox
Closes #207 
Add getTooltip() method that overrides parent method from inherited InfoBox class in HydrateReminderTimer class. 
No unit tests needed. Checked in game.
RuneLite Version: 1.8.33.3
=> Show informative tooltip when mouse is hovered over infobox

src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java, src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
Closes #195 
Added the POLITE personality inside [HydrateReminderPersonalityType.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java).
Added the POLITE dictionary into a separate function and then added the option to the switch case inside [HydrateBreakMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java)
No testing has been done, as the change only adds a new option for the hydration message sent to users. No new functionality was added nor a change in the project functionality was done.
(However, testing will be done if required.)
=> Added polite personality and dictionary for hydration reminder

.github/CODEOWNERS, .github/workflows/auto-author-assign.yml
Adding automation to set reviewers and assignees on pull requests
Closes #224
Automation for assignees is done by adding a new github action (https://github.com/marketplace/actions/auto-author-assign)
Automation for reviewer is done by changing the CODEOWNERS file in the .github folder (By adding one asterisk before the account name)
I tested by forking, and making my account as the CODEOWNER for that forked repo, and asking a friend to make a pull request to that repository, and observing the auto assigned reviewer and assignee
RuneLite Version: v1.1.1
I deleted the testing repository before making this pull request :/
=> Adding automation to set reviewers and assignees on pull requests

src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java, src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
Closes #191 
Added the MOTIVATIONAL personality inside [HydrateReminderPersonalityType.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java).
Added the MOTIVATIONAL dictionary into a separate function and then added the option to the switch case inside [HydrateBreakMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java)
No testing has been done, as the change only adds a new option for the hydration message sent to users. No new functionality was added nor a change in the project functionality was done.
(However, testing will be done if required.)
=> Add new hydrate message personality type: Motivational

src/test/java/com/hydratereminder/command/prev/PrevCommandHandlerTest.java
Closes #260 
Fixed failing tests in `PrevCommandHandlerTest.java` by migrating them to JUnit 5.
Operating System: macOS Monterey
RuneLite Version: N/A
=> Fix failing PrevCommandHandlerTest unit tests

src/main/java/com/hydratereminder/chat/HydrateEmojiProvider.java
Closes #274
Changed the generic exception that was being catched to a RuntimeException as the ImageUtils methods that are being used within the try block tend to return RuntimeException or IllegalArgumentException both of which would be taken care of by specifying RuntimeException
RuneLite Version: 1.9.0
=> Fix to avoid catching generic exception in HydrateEmojiProvider

src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
Closes #275 
I've refactored `getRandomPersonality()` method to return String instead of void, and added missing break statement in switch.
I've also noticed that `getRandomPersonality()` wasn't aware of `FUN` personality, so I've changed the logic to account for all personalities except `RANDOM`.
Operating System: Linux Mint 20.3 Cinnamon
RuneLite Version: 1.8.34.1
=> Fix implicit switch fall through issue

src/test/java/com/hydratereminder/HydrateReminderChatMessageTypeTest.java, src/test/java/com/hydratereminder/HydrateReminderCommandArgsTest.java, src/test/java/com/hydratereminder/HydrateReminderPluginTest.java, src/test/java/com/hydratereminder/HydrateReminderTimerImagesTest.java, src/test/java/com/hydratereminder/HydrateReminderTimerTest.java, src/test/java/com/hydratereminder/chat/ChatMessageSenderTest.java, src/test/java/com/hydratereminder/chat/ChatMessageTypeProviderTest.java, src/test/java/com/hydratereminder/chat/HydrateEmojiProviderTest.java, src/test/java/com/hydratereminder/command/CommandInvokerTest.java, src/test/java/com/hydratereminder/command/help/HelpCommandHandlerTest.java, src/test/java/com/hydratereminder/command/hydrate/HydrateCommandHandlerTest.java, src/test/java/com/hydratereminder/command/next/NextCommandHandlerTest.java, src/test/java/com/hydratereminder/command/prev/PrevCommandHandlerTest.java, src/test/java/com/hydratereminder/command/reset/ResetCommandHandlerTest.java, src/test/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionaryTest.java, src/test/java/com/hydratereminder/dictionary/HydrateWelcomeMessageDictionaryTest.java
Fixing Codacy issue:  JUnit 5 tests should be package-private.
Not have issue associated.
- Deleted public in test classes and methods.
- Removed wild card imports from test classes
- Reformat test classes
Run Unit tests after changes. All passed.
Operating System:  Windows 11
RuneLite Version:  N/A
=> (Codacy issue): JUnit 5 tests should be package-private

src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java, src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
* Add new personality type
* Add list of messages for new personality type
* Fix 2 typos in message dictionary class
Closes #268 
- Added new value for HydrateReminderPersonalityType enum: SANTA
- Added list of messages for SANTA
- By the way I fixed 2 typos in HydrateWelcomeMessageDictionary: 1. incorrect type in doc comment 2. typo in the message of romantic type
To push my changes, I needed to resolve conflicts with https://github.com/jmakhack/hydrate-reminder/issues/262
Tested by running HydrateReminderTest.java and verifying the changes in the application.
Operating System: Windows 10
RuneLite Version:  1.9.0
=> ﻿Add Santa personality type for hydrate reminder. Closes #268

src/main/java/com/hydratereminder/HydrateReminderConfig.java
Closes #333 
Corrected the variable names and occurrences as per Pascal casing.
Operating System: MacOS 12.6
RuneLite Version: 1.1.1
=> fix: rename variables as per Codacy review

src/main/java/com/hydratereminder/chat/ChatMessageSender.java
Closes #329 
surrounded the log statement with a log level guard to prevent unnecessary log printing
=> adde debug log level guard

src/main/java/com/hydratereminder/command/NotRecognizedCommandException.java, src/main/java/com/hydratereminder/command/NotSupportedCommandException.java
Closes #330 
Added **super()** in `src/main/java/com/hydratereminder/command/NotRecognizedCommandException.java` and `src/main/java/com/hydratereminder/command/NotSupportedCommandException.java`
RuneLite Version: 1.9.0
=> fix: add super() in constructor

src/main/java/com/hydratereminder/command/NotRecognizedCommandException.java, src/main/java/com/hydratereminder/command/NotSupportedCommandException.java, src/test/java/com/hydratereminder/command/CommandInvokerTest.java
Closes #352 
Modify command exception to use message instead of reason.
Missing a test for NotSupportedCommandException.
Operating System: Windows
=> modify command exception to use message instead of reason

src/test/java/com/hydratereminder/command/total/TotalCommandHandlerTest.java
Closes #327 
Removed public access modifier from the class to make it package private
=> Removing public access modifier to declare test package private

src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
Closes #294 
As detailed in the issue description, this PR removes the switch case pattern in the ```getRandomHydrateBreakMessageForPersonality``` method and instead creates a map that links the personalityType to the corresponding list of hydrate break messages
No change to existing behaviour. Ran the unit tests and observed no failure related to the PR.
=> Refactor getRandomHydrateBreakMessageForPersonality method

src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #138 
Changed class HydrateReminderPlugin, added new variable overlayIsPresent to check whether the Overlay Timer has been created already. Changed method onGameTick(): Overlay Timer is now only removed and created if it doesn't exist already. Changed methods createHydrateReminderOverlayTimer() and removeHydrateReminderOverlayTimer() to set the variable overlayIsPresent. 
Changed method onConfigChanged() to perform removal and creation of Overlay Timer every time a change in config (e.g. colour or image changed) is performed. The changes are now visible immediately, without checking and unchecking the Overlay Timer box. 
Operating System: Windows 11Pro 
=> Solved: Fix unnecessary removal and creation of overlay timer on every game tick #138

src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
Closes #380
Fixed the logic that is used to calculate the message to display when the random personality type is selected.
Operating System: macOS Monterey
=> Fix random personality not working issue
