- build.gradle
- src/test/java/com/hydratereminder/HydrateReminderChatMessageTypeTest.java
- src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #4
Wrote [jUnit](https://junit.org/junit4/) tests with [jMockit](https://jmockit.github.io/) as the mocking framework.
> Add jUnit tests

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
- src/test/java/com/hydratereminder/HydrateReminderChatMessageTypeTest.java
- src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #24
Addressed all the Codacy code quality issues.
Operating System: Manjaro Linux
RuneLite Version: 1.7.3.1
> Resolve code quality issues

- build.gradle
- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
- src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #28
Same as the next command but with the calculation of `now - lastbreak`.
Operating System: macOS Mojave
RuneLite Version: 1.7.4
> Add hydrate prev command

- README.md
Closes #38
Updated the README with screenshots and a new Plugin Functionality section which includes descriptions of all the features for the new v.1.1.0 release.
> Update README for v1.1.0 release

- build.gradle
- src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Just fixing some issues with the gradle dependencies so that the plugin can be published to the RuneLite plugin hub.
> Fix dependencies issue

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
Improved the issue templates by making them all have consistent formatting across them and by commenting out the examples and text similar to the pull request template.
> Improve issue templates

- src/main/java/com/hydratereminder/HydrateReminderConfig.java
- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
- src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #64
Kept the text consistent throughout by adding periods and referring to breaks as `hydration break` everywhere applicable.
Also moved the welcome message config to the top of the config list as it seems to make more sense in terms of ordering.
> Reorder config options and fix text inconsistencies

- README.md
- build.gradle
- src/main/java/com/hydratereminder/HydrateReminderConfig.java
Closes #75
Bumped the plugin version number to 1.1.1, bumped the RuneLite version to 1.7.16, and updated the documentation where necessary.
Also changed some of the default configurations for this release to make them less intrusive at default and to promote a better hydration interval.
RuneLite Version: 1.7.16
> Bump to version v1.1.1

- .all-contributorsrc
Changed contributors to 5 per row instead of 7.
> Change number of contributors per row

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #86
Added 18 strings to the ArrayList of hyrate reminder messages to meet the v1.2.0 goal of 30 total reminder messages.
Ran the unit tests defined in HydrateReminderChatMessageTypeTest and HydrateReminderPluginTest, both passing.
Attempted to run HydrateReminderTest, which successfully launched the game, but was unable to install the plugin and receive hydration reminders.
Operating System: Windows 10
RuneLite Version: 1.7.18
> Added additional strings to the hydrate reminder messages

- README.md
Closes #87
Added a form to provide questions, comments, and feedback in the README.
> Add feedback form

- README.md
Replaced one meme link with another because why not.
> Update made with love badge

- README.md
Same as previous PR #103 , but updated with new relevant video.
> Update Made with Love badge with new video

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #85 
Operating System: Windows 10
RuneLite Version: 1.7.24
> Added many more welcome messages.

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Adds to #143
Added a quote of W. H. Auden about hydrating.
Note the necesity of escaping (by \) quotes inside quotes (as this quote about drinking water is part of a string).
> Added a new hydrate welcome message

- build.gradle
- src/main/java/com/hydratereminder/HydrateReminderConfig.java
- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
- src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #146
Adding hydrate animation when hydrating.
I have added unit tests that are covering that functionality.
> Add hydrate animation

- src/main/java/com/hydratereminder/HydrateReminderConfig.java
Closes #141 (part of it)
This PR renames 'Overlay Timer Display' section to 'Overlay Timer Settings'
RuneLite Version: 1.8.29
> Rename 'Overlay Timer Display' to 'Overlay Timer Settings'

- src/main/java/com/hydratereminder/HydrateReminderConfig.java
Closes #148 
Added Animation Settings section that encapsulates logic connected with animation
RuneLite Version: 1.8.29
> Add animation settings section

- src/main/java/com/hydratereminder/HydrateReminderConfig.java
Closes #141
Settings section for notifications was added
RuneLite Version: 1.8.29
> Add notification settings section

- README.md
Added `Plugin Rank`, `Total Installs`, and `Stars` badges to README.
> Add plugin related badges to README

- README.md
- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #173 
I have replaced all the references to ::hydrate in favor of ::hr
> All references to ::hydrate changed to ::hr

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
- src/main/java/com/hydratereminder/dictionary/HydrateWelcomeMessageDictionary.java
Part of #99 
Extracted messages to dictionary class
No tests needed
> Extract welcome messages to dictionary

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #177 
removed the HYDRATE_WELCOME_TEXT_LIST class variable in HydrateReminderPlugin.java
- all tests were successful
- no build problems
tested using all 5 hydrateReminder tests available
> removed HYDRATE_WELCOME_TEXT_LIST class variable

- .github/ISSUE_TEMPLATE/task.md
Closes #183
Added a new issue template for tasks that includes sections for `Task Context`, `Acceptance Criteria / Goals`, and `Additional Notes`. Added a short and concise comment for each section to describe what should be included in each section.
Operating System: N/A
RuneLite Version: N/A
N/A
> Create new issue template for tasks

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #179 
Replaced string literal with string constant reference as detailed on issue
> add reference to String constant in helpString

- src/test/java/com/hydratereminder/dictionary/HydrateWelcomeMessageDictionaryTest.java
Closes #182 
Added single test case asserting non nullable and non empty welcome message.
> #182 add HydrateWelcomeMessageDictionaryTest

- CONTRIBUTING.md
Closes #123
Added a `Frequently Asked Questions` section within `CONTRIBUTING.md`. Though the list of questions is certainly not comprehensive in any way, this is mostly to just have a section in that doc that can always be added to and evolve over time.
> Update CONTRIBUTING.md with FAQ section

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/task.md
- CONTRIBUTING.md
- README.md
Closes #171
Updated `CONTRIBUTING.md` with info on how to setup the development environment and how to build and run the project. Updated `README.md` and also the new issue templates to direct people to `CONTRIBUTING.md` if they want to know how to properly setup their environment to work on this project.
> Setup build run docs

- SECURITY.md
Closes #187
Updated the security docs to show support for 2.x.x versions of the plugin.
Also made a slight edit to some of the wording.
> Update SECURITY.md with 2.x.x info

- src/main/java/com/hydratereminder/HydrateReminderConfig.java
Closes #178
Change `keyName` property
> Issue 178: Fix incorrect `keyName` property for `hydrateAnimationEnabled`

- src/main/java/com/hydratereminder/Commons.java
- src/main/java/com/hydratereminder/HydrateReminderCommandArgs.java
- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
- src/main/java/com/hydratereminder/command/Command.java
- src/main/java/com/hydratereminder/command/CommandCreator.java
- src/main/java/com/hydratereminder/command/CommandHandler.java
- src/main/java/com/hydratereminder/command/CommandInvoker.java
- src/main/java/com/hydratereminder/command/NotRecognizedCommandException.java
- src/main/java/com/hydratereminder/command/NotSupportedCommandException.java
- src/main/java/com/hydratereminder/command/help/HelpCommand.java
- src/main/java/com/hydratereminder/command/help/HelpCommandHandler.java
- src/main/java/com/hydratereminder/command/hydrate/HydrateCommand.java
- src/main/java/com/hydratereminder/command/hydrate/HydrateCommandHandler.java
- src/main/java/com/hydratereminder/command/next/NextCommand.java
- src/main/java/com/hydratereminder/command/next/NextCommandHandler.java
- src/main/java/com/hydratereminder/command/prev/PrevCommand.java
- src/main/java/com/hydratereminder/command/prev/PrevCommandHandler.java
- src/main/java/com/hydratereminder/command/reset/ResetCommand.java
- src/main/java/com/hydratereminder/command/reset/ResetCommandHandler.java
- src/main/java/com/hydratereminder/command/total/TotalCommand.java
- src/main/java/com/hydratereminder/command/total/TotalCommandHandler.java
- src/test/java/com/hydratereminder/HydrateReminderCommandArgsTest.java
Closes #99 
Prepared a skeleton for dividing command into separate classes.
We need to create follow-up issues to allow contributors to work on that refactoring.
Things that needs to be done (issues to be created):
- Extract message sender logic to separate class
- Extract `help` command logic to `HelpCommandHandler`
- Extract `hydrate` command logic to `HydrateCommandHandler`
- Extract `next` command logic to `NextCommandHandler`
- Extract `prev` command logic to `PrevCommandHandler`
- Extract `reset` command logic to `ResetCommandHandler`
- Extract `total` command logic to `TotalCommandHandler`
> Issue 99: Prepare commands and handlers for future refactoring

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/task.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
Closes #219
Created a new discord server at https://discord.gg/RTgxfFW9mS with a variety of channels, rules, webhooks, bots and more!
Linked the new discord on a various of project docs such as the README, CONTRIBUTING doc, and issue templates.
> Create discord server for hydrate-reminder

- build.gradle
- src/main/java/com/hydratereminder/HydrateReminderConfig.java
Improve hover tooltip description for animation setting
Closes #223
Update Animation tooltip to display "Enables a hydration animation that the player character performs every time the hydration interval completes"
Checked in client.
RuneLite Version: 1.8.33.3
> update tooltip description for animation setting

- README.md
- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
- src/main/java/com/hydratereminder/command/hydrate/HydrateCommandHandler.java
- src/test/java/com/hydratereminder/command/hydrate/HydrateCommandHandlerTest.java
Closes #213
Extracted hydrate command logic, add tests, update documentation
Simple unit tests included. 
In game test: Checked if the timer resetting, message appearing and hydration breaks increasing.
RuneLite Version: 1.8.34
Not needed
> Extract hydrate command logic to proper handler

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
- src/main/java/com/hydratereminder/command/next/NextCommandHandler.java
- src/test/java/com/hydratereminder/command/next/NextCommandHandlerTest.java
Closes #214 
`next` command logic was extracted to handler
> Issue 214: Extract next command logic to handler

- src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java
- src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
> added pirate personality type and 12 pirate messages.

- src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java
- src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
> Added Agressive Personality Hydrate Message

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
- src/main/java/com/hydratereminder/command/help/HelpCommandHandler.java
- src/test/java/com/hydratereminder/command/help/HelpCommandHandlerTest.java
Closes #212 
Command logic was extracted to proper handler class
> Issue 212: Extract help command logic to handler

- build.gradle
- src/test/java/com/hydratereminder/HydrateReminderChatMessageTypeTest.java
- src/test/java/com/hydratereminder/HydrateReminderCommandArgsTest.java
- src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
- src/test/java/com/hydratereminder/HydrateReminderTimerImagesTest.java
- src/test/java/com/hydratereminder/HydrateReminderTimerTest.java
- src/test/java/com/hydratereminder/chat/ChatMessageSenderTest.java
- src/test/java/com/hydratereminder/chat/ChatMessageTypeProviderTest.java
- src/test/java/com/hydratereminder/chat/HydrateEmojiProviderTest.java
- src/test/java/com/hydratereminder/command/help/HelpCommandHandlerTest.java
- src/test/java/com/hydratereminder/command/hydrate/HydrateCommandHandlerTest.java
- src/test/java/com/hydratereminder/command/next/NextCommandHandlerTest.java
- src/test/java/com/hydratereminder/command/reset/ResetCommandHandlerTest.java
- src/test/java/com/hydratereminder/command/total/TotalCommandHandlerTest.java
- src/test/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionaryTest.java
- src/test/java/com/hydratereminder/dictionary/HydrateWelcomeMessageDictionaryTest.java
Closes #241
All tests were migrated to JUnit 5
> Issue 241: Migrate to JUnit 5

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
- src/main/java/com/hydratereminder/command/CommandInvoker.java
- src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
- src/test/java/com/hydratereminder/chat/HydrateEmojiProviderTest.java
- src/test/java/com/hydratereminder/command/CommandInvokerTest.java
- src/test/java/com/hydratereminder/command/prev/PrevCommandHandlerTest.java
There are not any associated issue. This PR ending refactor of commands done in 211-217.
**_Note: This PR depends on PR #256. First 3 commits are from #256 PR._** 
Invoking commands is done by one command invoker method.
Chat messages showed when throw exceptions in CommandInvoker were added.
Added unit tests.
Add unit tests. Tested locally - screens.
RuneLite Version: 1.8.34.1
_**IT WAS TESTED BUT PLEASE TEST IT ON YOUR LOCAL AND LEAVE COMMENTS IF NEEDED **_
> Refactor invoking commands 

- src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java
- src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
Closes #200 
I have included the personality trait in Personality Type file and the solution I have implemented is that when RANDOM is called , a random number is generated from range 1 to 6 and all those number point towards a particular case and generate a random message from it/
> Added Random Function to Random Personality 

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
> Remove unused imports in HydrateReminderPlugin.java 

- src/main/java/com/hydratereminder/chat/ChatMessageSender.java
> Fixed concatenating characters as strings performance

- build.gradle
- src/main/java/com/hydratereminder/command/NotRecognizedCommandException.java
- src/main/java/com/hydratereminder/command/NotSupportedCommandException.java
Closes #279 
Add serialVersionUIDs to the exceptions to avoid **missing serialVersion version UID error**
RuneLite Version: 1.9.0
No screenshots
> add serialVersionUIDs to the exceptions

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #272
remove the mentioned initializers
> remove redundant initializers

- src/main/java/com/hydratereminder/chat/ChatMessageSender.java
> ChatMessageSender.java is modified

- CONTRIBUTING.md
Closes #324
Fixed indentation issues in CONTRIBUTION.md
> Fix no-paragraph-content-indent issue in CONTRIBUTING.md

- src/main/java/com/hydratereminder/HydrateReminderTimer.java
- src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
Closes #331 
Added underscore to resolve the issue
Operating System: Windows
> Fix use underscores in numeric literals issues

- build.gradle
- src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
- src/main/java/com/hydratereminder/dictionary/HydrateWelcomeMessageDictionary.java
- src/test/java/com/hydratereminder/HydrateReminderTest.java
Closes #292
Implemented [Utility Class from Lombok](https://www.baeldung.com/java-sonar-hide-implicit-constructor#3-using-lombok-utilityclass) to build a Utility Class as all the methods of the class were static methods.
RuneLite Version: 1.9.0
> fix: Use Utility Class issues

- CONTRIBUTING.md
- README.md
Fixes list-item-spacing in Documentation
Closes #325 
Fixed the spacing in the documentation according to the Codacy Static Code Analysis report.
> Fix list-item-spacing in Documentation

- src/main/java/com/hydratereminder/HydrateReminderConfig.java
for the issue #222 someone just add the same description for the `Timer Display` and `Computer notification`, I just re-enter the message, with the suitable message for `Timer Display`
> re-edit the message for timer-dispay for hydrate-reminder

- src/main/java/com/hydratereminder/HydrateReminderConfig.java
> Applied the Suggested Changes and Resolved #221

- src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java
- src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
- src/test/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionaryTest.java
> added kawaii personality type

- src/test/java/com/hydratereminder/chat/ChatMessageSenderTest.java
Closes #276 
I made the string as a private variable, so it won't be duplicated.
Just run all test to see if anything broke
> Updated ChatMessageSenderTest

- src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java
- src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java
- src/test/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionaryTest.java
Closes #192 
Added a new personality type through Arraylist and created an extra case for the switch
> Add hype personality

- .all-contributorsrc
Closes #371
Updated the contributorsPerLine to `7` from `5`.
Operating System: NA
RuneLite Version: NA
> update all-contributorsrc to show 7 contributors per line

- build.gradle
- src/test/java/com/hydratereminder/HydrateReminderChatMessageTypeTest.java
- src/test/java/com/hydratereminder/HydrateReminderCommandArgsTest.java
- src/test/java/com/hydratereminder/HydrateReminderImagesTest.java
- src/test/java/com/hydratereminder/HydrateReminderPluginTest.java
- src/test/java/com/hydratereminder/HydrateReminderTest.java
- src/test/java/com/hydratereminder/HydrateReminderTimerTest.java
- src/test/java/com/hydratereminder/chat/ChatMessageSenderTest.java
- src/test/java/com/hydratereminder/chat/ChatMessageTypeProviderTest.java
- src/test/java/com/hydratereminder/chat/HydrateEmojiProviderTest.java
- src/test/java/com/hydratereminder/command/CommandInvokerTest.java
- src/test/java/com/hydratereminder/command/help/HelpCommandHandlerTest.java
- src/test/java/com/hydratereminder/command/hydrate/HydrateCommandHandlerTest.java
- src/test/java/com/hydratereminder/command/next/NextCommandHandlerTest.java
- src/test/java/com/hydratereminder/command/prev/PrevCommandHandlerTest.java
- src/test/java/com/hydratereminder/command/reset/ResetCommandHandlerTest.java
- src/test/java/com/hydratereminder/command/total/TotalCommandHandlerTest.java
- src/test/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionaryTest.java
- src/test/java/com/hydratereminder/dictionary/HydrateWelcomeMessageDictionaryTest.java
Closes #386
Added comments in test files and refactored several tests. Also added messages to assertions.
Operating System: N/A
RuneLite Version: N/A
> Cleanup and refactor jUnit tests

- src/test/java/com/hydratereminder/HydrateReminderImagesTest.java
Closes #338 
Refactored test case to a parameterized test case.
Operating System: N/A
RuneLite Version: N/A
> Parameterize JUnit Test: testImagesGetID

- src/main/java/com/hydratereminder/HydrateReminderPlugin.java
Closes #394
After setting the animation value in the code, the animation frame is now set to 0 to ensure that the animation played will always start from frame 0.
Operating System: macOS Monterey
> Fix animation inconsistency issue

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/task.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
Updating docs and docstrings which are now outdated
> Update outdated docs
